In [1]:
import re
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
import argparse
import datetime
import requests
from lxml import html
import lxml.html as lh
from bs4 import BeautifulSoup
import warnings 
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('df_file')

In [3]:
# Tried WebScraping
a = list(df.loc[:,'education']=='None')
count = -1
none_education_list = []
for i in a:
    count +=1
    if i == True:
        none_education_list.append(count)
len(none_education_list)

2208

In [4]:
def web_scraping_education(df_col):
    header = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36'}
    page_url = 'https://en.wikipedia.org/wiki/'
    edu_url=[]
    for i in none_education_list:
        req = requests.get(page_url+df_col[i], headers=header)
        soup = BeautifulSoup(req.text, 'lxml')

        edu_find = soup.find('table', attrs={'class': 'infobox biography vcard'})
        edu_url.append(str(edu_find))

    edu_l =[]
    for j in edu_url:
        edu_l.append(re.findall('Alma', j) or re.findall('Education', j))
    print(edu_l)
    edu = []
    for x in edu_l:
        if len(x) !=0:
            edu.append('Yes')
        else:
            edu.append('No')
    
    return edu

In [5]:
education = web_scraping_education(df.name)

[['Education'], [], ['Alma'], ['Alma'], [], [], ['Alma'], ['Alma'], ['Education', 'Education', 'Education'], ['Alma'], [], ['Alma'], ['Alma'], ['Education'], ['Education'], ['Education'], ['Alma'], [], ['Alma'], [], [], ['Alma'], [], ['Alma'], [], ['Education'], [], ['Alma'], ['Education'], [], ['Education'], ['Education'], [], ['Alma'], [], [], ['Alma'], ['Education'], [], ['Education'], [], [], ['Alma'], ['Education'], ['Education'], [], [], [], ['Education'], [], [], ['Education'], ['Education'], ['Education'], [], ['Alma'], ['Education'], ['Alma'], ['Alma'], ['Alma'], ['Alma'], ['Alma'], [], ['Alma'], [], ['Alma'], ['Alma'], ['Education'], [], ['Alma'], ['Education'], [], [], [], ['Alma'], [], [], ['Alma'], ['Alma'], ['Alma'], [], [], ['Alma'], ['Alma'], ['Alma'], [], [], ['Education'], [], [], [], ['Education'], ['Alma'], ['Alma'], [], [], ['Alma'], ['Alma'], ['Alma'], ['Alma'], [], [], ['Alma'], ['Alma'], [], [], ['Alma'], ['Alma'], [], ['Education'], [], ['Alma'], ['Alma'], ['Education'], ['Alma'], [], [], ['Alma'], ['Alma'], ['Alma'], ['Alma'], ['Education'], ['Alma'], [], [], [], ['Alma'], [], ['Alma'], [], ['Education'], [], [], [], [], ['Education'], [], [], ['Alma'], [], ['Alma'], [], ['Education'], ['Education'], ['Education'], [], [], ['Alma'], ['Alma'], [], [], ['Alma'], ['Alma'], [], [], [], ['Alma'], [], ['Alma'], ['Alma'], [], [], [], [], [], ['Education'], [], [], [], ['Alma'], ['Alma'], ['Education'], [], [], ['Alma'], ['Education'], ['Alma'], [], [], [], [], ['Education'], [], ['Education'], ['Alma'], [], ['Education'], ['Education'], [], [], ['Alma'], ['Alma'], [], ['Education'], ['Education'], [], [], ['Alma'], ['Alma'], ['Alma'], [], ['Education'], ['Alma'], ['Education'], [], [], ['Alma'], [], ['Alma'], ['Alma'], ['Alma'], ['Education'], ['Alma'], [], ['Education'], [], ['Alma'], [], [], [], ['Education'], ['Alma'], ['Education'], [], [], ['Education'], [], [], [], [], ['Alma'], ['Alma'], [], ['Alma'], ['Alma'], [], [], [], ['Education'], ['Alma'], [], [], [], [], [], [], [], ['Alma'], [], [], ['Education'], ['Alma'], ['Education'], [], [], [], [], ['Alma'], ['Education'], ['Alma'], ['Alma'], ['Alma'], ['Alma'], [], [], ['Alma'], [], ['Education'], [], [], [], ['Alma'], ['Education'], [], [], [], [], ['Alma'], ['Alma'], [], [], ['Education'], ['Alma'], ['Alma'], ['Alma'], [], ['Education'], ['Alma'], ['Education'], ['Education'], [], [], ['Education'], ['Education'], [], [], ['Alma'], [], [], ['Education'], ['Alma'], [], ['Education'], ['Alma'], [], [], [], ['Education'], [], [], ['Alma'], [], [], ['Alma'], [], [], ['Alma'], ['Alma'], [], ['Alma'], [], [], ['Alma'], [], [], [], [], [], ['Alma'], ['Education'], ['Alma'], [], [], [], ['Education'], [], [], [], [], ['Education'], [], [], ['Alma'], ['Alma'], [], [], ['Education'], ['Alma'], ['Education', 'Education', 'Education'], ['Education'], [], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], ['Alma'], [], ['Alma'], ['Alma'], [], [], [], ['Education'], ['Education'], ['Education'], [], ['Alma'], ['Alma'], ['Alma'], [], [], ['Education'], [], ['Education'], ['Education'], ['Education'], [], ['Education'], [], [], ['Education'], ['Education'], [], [], [], [], [], [], ['Education'], ['Education'], ['Alma'], [], [], [], ['Alma'], ['Alma'], [], [], ['Alma'], ['Education'], [], ['Education'], ['Education'], [], ['Alma'], [], ['Education'], [], ['Alma'], [], ['Education'], [], [], ['Alma'], ['Alma'], ['Alma'], [], [], ['Alma'], [], ['Education'], ['Alma'], [], [], [], [], ['Alma'], ['Education'], ['Alma'], [], [], [], ['Alma'], [], ['Education'], ['Alma'], [], [], [], ['Education'], [], ['Alma'], ['Alma'], [], ['Alma'], ['Alma'], [], [], [], [], [], [], ['Alma'], [], ['Alma'], ['Education'], [], [], [], [], ['Alma'], [], [], [], [], [], ['Alma'], [], [], [], [], [], ['Education'], [], ['Alma'], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], ['Alma'], [], ['Alma'], [], ['Alma'], ['Alma'], ['Alma'], ['Education'], ['Alma'], ['Alma'], ['Alma'], ['Education'], ['Alma'], [], ['Alma'], [], ['Education'], [], [], [], ['Education'], [], [], ['Education'], [], ['Education'], [], [], ['Education'], ['Alma'], ['Education'], [], [], [], [], ['Alma'], [], ['Alma'], ['Alma'], ['Alma'], ['Education'], [], [], ['Alma'], ['Alma'], [], ['Education'], ['Education'], [], ['Alma'], ['Education'], ['Alma'], ['Alma'], [], [], [], ['Alma'], [], ['Alma'], [], [], [], [], [], ['Alma'], [], ['Alma'], [], [], [], ['Alma'], [], [], [], [], ['Alma'], ['Alma'], ['Education'], [], [], [], [], [], ['Alma'], [], ['Alma'], [], [], ['Alma'], [], ['Education'], ['Education'], [], ['Alma'], [], ['Education'], [], ['Education'], [], [], [], [], ['Education'], [], ['Alma'], ['Alma'], [], [], [], ['Education'], ['Alma'], ['Alma'], ['Alma'], ['Alma'], [], ['Alma'], [], [], ['Education'], [], [], [], [], [], ['Alma'], ['Alma'], [], [], [], [], ['Alma'], [], [], ['Alma'], [], [], [], ['Alma'], [], [], ['Alma'], ['Education'], [], [], [], [], ['Alma'], ['Alma'], [], ['Alma'], ['Education'], [], ['Education'], ['Education'], [], [], [], [], [], [], [], [], ['Alma'], [], [], ['Education'], ['Alma'], ['Education'], ['Alma'], [], [], [], ['Alma'], [], ['Alma'], [], [], ['Alma'], [], [], [], [], [], ['Alma'], [], ['Alma'], [], [], ['Alma'], ['Education'], ['Alma'], [], ['Alma'], [], [], ['Alma'], ['Alma'], [], [], [], [], ['Alma'], [], [], ['Alma'], [], [], [], ['Education'], [], [], [], [], [], ['Alma'], ['Education'], ['Alma'], [], [], [], ['Alma'], [], ['Alma'], ['Education'], [], ['Alma'], [], ['Education'], [], ['Alma'], ['Education'], ['Education'], [], ['Alma'], [], [], ['Alma'], [], ['Alma'], [], ['Alma'], ['Alma'], ['Alma'], ['Alma'], [], [], ['Alma', 'Alma', 'Alma', 'Alma'], [], ['Alma'], ['Alma'], [], [], [], [], [], ['Alma'], ['Education'], ['Alma'], [], [], [], [], [], [], [], [], [], ['Education'], [], [], [], [], ['Alma'], [], [], [], [], ['Alma'], [], ['Alma'], [], [], [], [], [], ['Alma'], ['Alma'], [], [], [], [], ['Alma'], [], [], ['Alma'], ['Alma'], ['Alma'], ['Education'], ['Education'], [], [], [], ['Education'], [], ['Education'], ['Alma'], ['Alma'], [], [], [], [], ['Alma'], [], [], ['Alma'], ['Education'], [], [], [], [], [], [], [], [], ['Alma'], [], [], ['Education'], [], [], [], [], ['Alma'], ['Alma'], ['Alma'], ['Alma'], ['Alma'], [], [], ['Alma'], [], [], ['Alma'], [], ['Education'], [], [], [], ['Education'], [], ['Education'], ['Education'], [], [], [], [], [], ['Education'], ['Alma'], [], [], ['Alma'], [], ['Alma'], [], ['Alma'], [], [], [], [], [], [], [], [], ['Education'], ['Education'], ['Alma'], [], [], [], [], ['Alma'], ['Alma'], ['Alma'], [], ['Education'], ['Alma'], [], ['Alma'], ['Alma'], ['Alma'], [], [], ['Alma'], [], [], [], [], [], [], [], ['Alma'], ['Alma'], [], ['Education'], [], [], [], [], [], ['Alma'], [], ['Education'], [], ['Education'], [], [], [], ['Alma'], [], ['Alma'], [], ['Education'], ['Alma'], ['Education'], [], ['Education'], ['Alma'], [], ['Alma'], ['Alma'], [], ['Education'], ['Alma'], [], ['Alma'], [], ['Alma'], [], ['Alma'], ['Alma'], [], [], [], [], [], ['Alma'], [], [], [], ['Education'], ['Alma'], [], ['Alma'], [], [], [], [], ['Alma'], [], [], ['Alma'], [], ['Education'], ['Alma'], [], ['Education'], ['Education'], [], ['Education'], [], [], ['Alma'], ['Alma'], [], [], [], [], [], ['Education'], ['Alma'], ['Education'], [], ['Alma'], [], [], ['Alma'], [], [], [], ['Education'], ['Alma'], [], ['Alma', 'Alma', 'Alma'], ['Alma'], ['Alma'], ['Alma'], [], [], ['Alma'], [], ['Education'], [], ['Alma'], [], ['Alma'], [], [], ['Education'], [], [], [], ['Alma'], [], [], ['Alma'], [], ['Education'], ['Alma'], ['Alma'], [], [], ['Alma'], ['Education'], ['Alma'], [], [], [], [], [], [], [], [], [], [], ['Alma'], [], [], [], [], [], [], ['Alma'], ['Education'], [], [], ['Alma'], ['Education'], [], [], ['Alma'], [], [], [], [], [], [], ['Alma'], ['Education'], [], [], ['Alma'], [], [], ['Education'], [], [], ['Alma'], ['Education', 'Education', 'Education'], [], [], ['Alma'], [], [], ['Alma'], [], [], ['Alma'], [], ['Alma'], ['Alma'], [], [], [], [], [], [], [], ['Alma'], [], [], [], [], [], [], ['Alma'], [], [], [], ['Alma'], [], [], [], [], [], [], [], ['Education'], [], ['Alma'], [], [], [], ['Alma'], [], [], [], [], ['Alma'], [], [], [], ['Alma'], [], ['Alma'], ['Alma'], [], ['Alma'], [], [], [], [], [], [], ['Alma'], ['Education'], [], [], [], ['Alma'], ['Alma'], [], [], [], ['Alma'], [], [], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Education'], [], [], [], ['Alma'], ['Alma'], ['Alma'], ['Education'], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Alma'], [], [], [], ['Alma'], [], [], ['Alma'], [], [], [], [], [], [], [], [], [], ['Alma'], [], [], [], [], ['Alma'], [], [], ['Education'], [], [], [], [], [], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], ['Alma'], [], ['Education'], ['Alma'], [], [], [], [], [], [], ['Alma'], ['Alma'], ['Alma'], [], ['Education'], [], [], [], ['Alma'], [], [], [], [], [], [], [], [], [], ['Alma'], [], [], [], [], ['Education'], ['Education'], [], ['Alma'], ['Alma'], ['Alma'], [], [], [], ['Alma', 'Alma', 'Alma'], [], [], [], [], [], ['Education'], [], ['Alma'], [], ['Education'], [], [], [], [], [], [], [], [], ['Alma'], [], [], [], ['Alma'], ['Alma'], [], [], [], [], [], [], [], [], [], ['Education'], [], ['Alma'], [], [], [], ['Education'], [], [], ['Education'], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], ['Education'], [], [], [], [], [], [], [], ['Education'], [], [], [], ['Alma'], ['Alma'], [], [], [], [], ['Alma'], ['Alma'], [], [], [], [], [], [], ['Alma'], [], ['Education'], [], [], [], ['Alma'], [], [], [], ['Alma'], ['Alma'], [], [], [], [], [], [], [], [], [], [], ['Alma'], [], [], [], [], [], [], [], ['Alma'], [], [], [], [], [], [], [], [], ['Alma'], ['Education'], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Alma'], [], [], [], ['Alma'], [], [], [], ['Alma'], ['Education'], [], ['Education'], [], [], [], [], [], [], [], [], ['Education'], [], [], [], [], [], [], [], [], ['Alma'], [], [], [], [], [], ['Alma'], [], ['Alma'], [], ['Alma'], [], [], [], [], [], [], [], [], ['Alma'], [], [], ['Education'], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], ['Alma'], ['Alma'], [], [], [], ['Alma'], ['Alma'], ['Education'], [], ['Alma'], [], [], [], [], [], [], [], [], [], ['Education'], [], [], [], [], [], ['Alma'], ['Alma'], [], [], ['Alma'], ['Alma'], [], ['Alma'], [], [], [], [], ['Alma'], ['Alma'], [], [], [], [], [], [], [], ['Alma'], [], [], [], [], ['Education'], ['Education'], [], [], [], ['Education'], ['Education'], [], ['Alma'], [], ['Education'], [], [], [], [], [], [], [], [], [], [], [], ['Alma'], [], [], [], ['Alma'], ['Alma'], ['Alma'], [], ['Alma'], [], [], [], [], [], ['Education'], [], ['Education'], [], [], ['Education'], ['Alma'], [], [], [], [], [], [], [], ['Alma'], ['Alma'], [], [], [], ['Education'], [], ['Alma'], [], [], ['Education'], [], [], [], ['Education'], [], [], ['Alma'], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Alma'], ['Alma'], [], ['Alma'], ['Education'], [], [], [], [], ['Alma'], [], ['Alma'], [], [], [], [], [], ['Alma'], [], [], [], [], ['Education'], [], [], ['Alma'], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Alma'], [], [], [], [], [], [], ['Education'], ['Alma'], ['Alma'], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], ['Alma'], ['Education'], [], [], [], [], ['Alma'], ['Alma'], [], [], [], [], ['Alma'], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], ['Education'], ['Alma'], [], [], [], [], [], [], [], [], [], [], ['Alma'], ['Education'], [], [], ['Education'], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Education'], [], [], ['Alma'], [], [], [], [], [], [], [], ['Alma'], [], [], [], [], [], ['Education'], [], [], [], ['Education'], ['Alma'], ['Education'], [], [], [], [], [], [], [], ['Education'], [], [], [], ['Education'], [], [], ['Alma'], [], [], ['Alma'], ['Alma'], ['Education'], [], [], [], [], [], [], ['Alma'], ['Alma'], [], [], [], [], [], [], [], ['Education'], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], ['Alma'], ['Alma'], ['Education'], [], [], [], [], [], [], [], [], ['Education'], [], [], [], ['Education'], [], [], [], [], [], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], ['Alma'], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Alma'], [], [], ['Alma'], [], ['Alma'], [], [], [], [], ['Education'], [], [], [], ['Education'], [], ['Alma'], [], ['Alma'], [], [], [], [], [], [], ['Alma'], [], [], [], ['Education'], [], [], [], ['Alma'], ['Education'], [], [], [], [], [], [], [], [], [], ['Alma', 'Alma', 'Alma'], [], [], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Education'], [], [], [], [], [], [], [], [], [], [], [], [], ['Alma'], ['Alma'], [], [], [], [], [], ['Alma'], [], [], [], ['Alma'], ['Education'], [], [], [], ['Education'], ['Alma'], [], [], [], [], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Alma'], [], [], [], ['Alma'], ['Alma'], [], [], [], ['Alma'], [], [], ['Education'], [], [], [], [], [], [], [], [], [], [], ['Alma'], [], [], [], [], [], ['Alma'], [], [], ['Education'], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Education'], [], ['Alma'], [], [], ['Education'], [], [], [], [], [], [], [], [], [], [], ['Education'], [], [], [], [], [], [], [], ['Alma'], [], ['Alma'], [], [], [], ['Alma'], ['Alma'], [], [], [], [], [], [], ['Alma'], [], [], [], [], ['Education'], [], [], [], [], [], [], [], [], [], ['Alma'], [], [], ['Alma'], [], [], [], [], [], [], ['Alma'], ['Education'], [], [], [], [], [], [], [], [], [], [], [], [], ['Education'], [], [], [], ['Education'], [], [], [], [], [], [], [], ['Alma'], [], [], [], [], [], [], [], [], [], [], ['Alma'], ['Alma'], [], ['Alma'], [], [], [], [], ['Alma'], [], ['Alma'], [], [], ['Education'], [], ['Alma'], [], [], [], [], ['Education'], [], [], [], [], [], ['Alma'], [], [], [], [], [], [], [], [], []]

In [6]:
df['education'] = education
df

,first_name,last_name,age,gender,country,position,real_time_position,worth(BUSD),worth(millions_USD),work_field,company,image,name,education
0,Jeff,Bezos,54,M,United States,1.0,1.0,112.0,0.000,Technology,Amazon,https://specials-images.forbesimg.com/imageser...,Jeff_Bezos,Yes
1,Bill,Gates,62,M,United States,2.0,2.0,90.0,-0.001,Technology,Microsoft,https://specials-images.forbesimg.com/imageser...,Bill_Gates,No
2,Warren,Buffett,87,M,United States,3.0,3.0,84.0,-0.002,Finance and Investments,Berkshire Hathaway,https://specials-images.forbesimg.com/imageser...,Warren_Buffett,Yes
3,Bernard,Arnault,69,M,France,4.0,4.0,72.0,0.000,Fashion & Retail,Lvmh,https://specials-images.forbesimg.com/imageser...,Bernard_Arnault,Yes
4,Mark,Zuckerberg,34,M,United States,5.0,5.0,71.0,0.000,Technology,Facebook,https://specials-images.forbesimg.com/imageser...,Mark_Zuckerberg,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2203,Zhao,Xiaoqiang,51,M,China,2204.0,2134.0,1.0,0.000,Fashion & Retail,"Fashion, Entertainment",https://specials-images.forbesimg.com/imageser...,Zhao_Xiaoqiang,No
2204,Zhou,Liangzhang,55,M,China,2205.0,2134.0,1.0,NaN,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...,Zhou_Liangzhang,No
2205,Zhu,Xingming,51,M,China,2206.0,1856.0,1.0,0.000,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...,Zhu_Xingming,No
2206,Jun,Zhuo,52,F,Hong Kong,2207.0,1978.0,1.0,0.000,Manufacturing,Printed Circuit Boards,https://specials-images.forbesimg.com/imageser...,Jun_Zhuo,No
2207,Olgun,Zorlu,54,M,Turkey,2208.0,1978.0,1.0,NaN,Diversified,Diversified,https://specials-images.forbesimg.com/imageser...,Olgun_Zorlu,No

In [10]:
df.drop('name', axis=1, inplace=True)

In [12]:
df.to_csv('final_csv')
df

,first_name,last_name,age,gender,country,position,real_time_position,worth(BUSD),worth(millions_USD),work_field,company,image,education
0,Jeff,Bezos,54,M,United States,1.0,1.0,112.0,0.000,Technology,Amazon,https://specials-images.forbesimg.com/imageser...,Yes
1,Bill,Gates,62,M,United States,2.0,2.0,90.0,-0.001,Technology,Microsoft,https://specials-images.forbesimg.com/imageser...,No
2,Warren,Buffett,87,M,United States,3.0,3.0,84.0,-0.002,Finance and Investments,Berkshire Hathaway,https://specials-images.forbesimg.com/imageser...,Yes
3,Bernard,Arnault,69,M,France,4.0,4.0,72.0,0.000,Fashion & Retail,Lvmh,https://specials-images.forbesimg.com/imageser...,Yes
4,Mark,Zuckerberg,34,M,United States,5.0,5.0,71.0,0.000,Technology,Facebook,https://specials-images.forbesimg.com/imageser...,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2203,Zhao,Xiaoqiang,51,M,China,2204.0,2134.0,1.0,0.000,Fashion & Retail,"Fashion, Entertainment",https://specials-images.forbesimg.com/imageser...,No
2204,Zhou,Liangzhang,55,M,China,2205.0,2134.0,1.0,NaN,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...,No
2205,Zhu,Xingming,51,M,China,2206.0,1856.0,1.0,0.000,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...,No
2206,Jun,Zhuo,52,F,Hong Kong,2207.0,1978.0,1.0,0.000,Manufacturing,Printed Circuit Boards,https://specials-images.forbesimg.com/imageser...,No
2207,Olgun,Zorlu,54,M,Turkey,2208.0,1978.0,1.0,NaN,Diversified,Diversified,https://specials-images.forbesimg.com/imageser...,No

In [7]:
# To replace the None values from colun country for the values of the list of countries that I just web scraped 
# from wikipedia first is necessary to convert 'None' to actually null values:
df['country'] = df.country.replace('None', np.nan).astype(object)

# The following command will give us the total of nulls in that specific column:
df.country.isnull().sum()

0

In [8]:
# Since the command df.fillna doesn't accept lists as values, we need to transform it into a dictionary:
dictionary = dict(zip(none_country_list, country_name))
dictionary

NameError: name 'none_country_list' is not defined

In [ ]:
# Finally we can use the command fillna available in pandas to fill the nulls with respective values:
df.country.fillna(value=dictionary, inplace=True)

In [ ]:
# Since the synthase of the values from the web we scraped on wasn't the same we need to change it:
df['country'].replace('U.S', 'United States', inplace=True)
df['country'].replace('Union', 'Soviet Union', inplace=True)
df['country'].replace("People's Republic of China", 'China', inplace=True)
display(df)

In [ ]:
null_age = df[df['age'].isnull()].index.tolist()
len(null_age)

In [ ]:
# What I've seen is that all null age values exist because there're two names in these columns:
#for i in null_age:
#    df.loc[i,'name'] = re.sub(' & ', '_and_', df.loc[i,'name'])
#    df.loc[i,'name'] = re.sub(' ', '_', df.loc[i,'name'])

In [ ]:
# Tentar WEBSCRAPING POR GOOGLE COM O SIMBOLO &:
df.loc[54, 'age'] = 105
df.loc[76, 'age'] = 65
df.loc[89, 'age'] = 77
df.loc[129, 'age'] = 79
df.loc[141, 'age'] = 67
df.loc[223, 'age'] = 85
df.loc[224, 'age'] = 75
df.loc[243, 'age'] = 66
df.loc[253, 'age'] = 73
df.loc[268, 'age'] = 55
df.loc[295, 'age'] = 55
df.loc[326, 'age'] = 89
df.loc[357, 'age'] =Family_Kwee
df.loc[358, 'age'] = 40
df.loc[363, 'age'] =Wai_Ying_Lam
df.loc[405, 'age'] = 36
df.loc[414, 'age'] = 69
df.loc[421, 'age'] = 71
df.loc[455, 'age'] = 93 
df.loc[465, 'age'] = 27
df.loc[550, 'age'] = 59
df.loc[579, 'age'] = 68
df.loc[581,'age'] = 60
df.loc[596,'age'] = 65
df.loc[600,'age'] = 38
df.loc[645,'age'] = 55
df.loc[656,'age'] = Gabriele_Volkmann
df.loc[668,'age'] = 72
df.loc[694,'age'] = 70
df.loc[703,'age'] = 70
df.loc[731,'age'] = Abdulla_Al_Futtaim
df.loc[823,'age'] = 71
df.loc[889,'age'] = Jose_And_Francisco_Jose_Calderon_Rojas
df.loc[916,'age'] =
df.loc[1008,'age'] =
df.loc[1028,'age'] =
df.loc[1078,'age'] =
df.loc[1108,'age'] =
df.loc[1133,'age'] =
df.loc[1143,'age'] =
df.loc[1154,'age'] =
df.loc[1182,'age'] =
df.loc[1230,'age'] =
df.loc[1289,'age'] =
df.loc[1290,'age'] =
df.loc[1383,'age'] =
df.loc[1502,'age'] =
df.loc[1560,'age'] =
df.loc[1632,'age'] =
df.loc[1718,'age'] =
df.loc[1719,'age'] =
df.loc[1750,'age'] =
df.loc[1786,'age'] =
df.loc[1807,'age'] =
df.loc[1826,'age'] =Di_Lu
df.loc[1856,'age'] =Karin_Schick
df.loc[1867,'age'] =Meirong_Yang
df.loc[1868,'age'] = Fawzi_Al-Kharafi
df.loc[2010,'age'] = Mohannad_Al-Kharafi
df.loc[2019,'age'] = Manas_Chiaravanond
df.loc[2020,'age'] = Yupa_Chiaravanond
df.loc[2021,'age'] = 67
df.loc[2028, 'age'] = 56
df.loc[2044, 'age'] = 62
df.loc[2117, 'age'] = 38

In [ ]:
df.loc[268, 'name']

In [ ]:
for i in null_age:
    print(df.loc[i, 'name'])

In [ ]:
def web_scraping_bday(df_col):
    header = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36'}
    page_url = 'https://en.wikipedia.org/wiki/'
    age_url=[]
    count=0
    for i in null_age[:5]:
        req = requests.get(page_url+df_col[i], headers=header)
        soup = BeautifulSoup(req.text, 'lxml')

        age_find = soup.find('span', attrs={'class': 'bday'})
        age_url.append(str(age_find))
        print(age_url)
    age_l=[]
    for j in age_url:
        age_l.append(re.findall('[0-9]+', j))
    print(type(age_url[1]))
    return age_l

In [ ]:
age = web_scraping_bday(df.name)
age

In [25]:
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import argparse
import requests
from lxml import html
import lxml.html as lh
from bs4 import BeautifulSoup

df = pd.read_csv('../package1/df_cleaned')

a = list(df.loc[:, 'education'] == 'None')
count = -1
none_education_list = []
for i in a:
    count += 1
    if i == True:
        none_education_list.append(count)


def web_scraping_education(df_col):
    header = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36'}
    page_url = 'https://en.wikipedia.org/wiki/'
    edu_url = []
    for i in none_education_list:
        req = requests.get(page_url + df_col[i], headers=header)
        soup = BeautifulSoup(req.text, 'lxml')

        edu_find = soup.find('table', attrs={'class': 'infobox biography vcard'})
        edu_url.append(str(edu_find))

    edu_l = []
    for j in edu_url:
        edu_l.append(re.findall('Alma', j) or re.findall('Education', j))

    edu = []
    for x in edu_l:
        if len(x) != 0:
            edu.append('Yes')
        else:
            edu.append('No')

def webscraping():

    df['education'] = web_scraping_education(df.name)

    df.drop('name', axis=1, inplace=True)
    print(df)
    #return df.to_csv('final_csv')

webscraping()

      first_name   last_name  age gender        country education  \
0           Jeff       Bezos   54      M  United States      None
1           Bill       Gates   62      M  United States      None
2         Warren     Buffett   87      M  United States      None
3        Bernard     Arnault   69      M         France      None
4           Mark  Zuckerberg   34      M  United States      None
...          ...         ...  ...    ...            ...       ...
2203        Zhao   Xiaoqiang   51      M          China      None
2204  Liangzhang        Zhou   55      M          China      None
2205    Xingming         Zhu   51      M          China      None
2206         Jun        Zhuo   52      F      Hong Kong      None
2207       Olgun       Zorlu   54      M         Turkey      None

      real_time_position  worth(BUSD)  worth(millions_USD)  \
0                      1        112.0                0.000
1                      2         90.0               -0.001
2                      3         84.0               -0.002
3                      4         72.0                0.000
4                      5         71.0                0.000
...                  ...          ...                  ...
2203                2134          1.0                0.000
2204                2134          1.0                  NaN
2205                1856          1.0                0.000
2206                1978          1.0                0.000
2207                1978          1.0                  NaN

                    work_field                 company  \
0                  Technology                   Amazon
1                  Technology                Microsoft
2     Finance and Investments       Berkshire Hathaway
3            Fashion & Retail                     Lvmh
4                  Technology                 Facebook
...                        ...                     ...
2203         Fashion & Retail   Fashion, Entertainment
2204            Manufacturing     Electrical Equipment
2205            Manufacturing     Electrical Equipment
2206            Manufacturing   Printed Circuit Boards
2207              Diversified              Diversified

                                                  image
0     https://specials-images.forbesimg.com/imageser...
1     https://specials-images.forbesimg.com/imageser...
2     https://specials-images.forbesimg.com/imageser...
3     https://specials-images.forbesimg.com/imageser...
4     https://specials-images.forbesimg.com/imageser...
...                                                 ...
2203  https://specials-images.forbesimg.com/imageser...
2204  https://specials-images.forbesimg.com/imageser...
2205  https://specials-images.forbesimg.com/imageser...
2206  https://specials-images.forbesimg.com/imageser...
2207  https://specials-images.forbesimg.com/imageser...

[2208 rows x 12 columns]